[theme]
primaryColor = "#001dff"               # warna utama (tombol, link aktif, dsb)
backgroundColor = "#e0f7fa"            # warna background halaman (abu-abu muda / aqua)
secondaryBackgroundColor = "#ffffff"   # warna background sidebar
textColor = "#004d40"                  # warna teks
font = "sans serif"
